version: '3'

services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - log-directory:/var/lib/postgresql/data

  backend:
    build: .
    command: uvicorn main:app --port 80 --host 0.0.0.0 --reload
    ports: 
      - 80:80
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  log-directory:
